name: flutter_app
description: "PDFCraft Studio Desktop Application"
publish_to: 'none'

version: 1.2.7+18

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdfx: ^2.9.2
  file_picker: ^11.0.2
  path: ^1.9.0
  path_provider: ^2.1.6
  desktop_drop: ^0.7.1
  url_launcher: ^6.3.2
  pdf: ^3.12.0
  crypto: ^3.0.3
  phosphor_flutter: ^2.1.0
  flex_color_scheme: 8.4.0
  google_fonts: 8.2.1
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  msix: ^3.18.0

dependency_overrides:
  path_provider_android: 2.2.15

msix_config:
  display_name: PDFCraft Studio
  publisher_display_name: على نورالدين السيد حسانين
  identity_name: A038805C.PDFCraftStudio
  publisher: CN=B8C022D6-3210-47E4-86DC-449784967308
  msix_version: 1.2.7.0
  logo_path: assets/app_icon.png
  store: true

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
